

classe E1 extende RuntimeException {}

classe E2 extende Exception {}
classe E3 extende Exception {}

func aa( x, y ) tratar E3 {
    se ( x > 10 )
        lance novo E3();
    retorne x+y;
}


func bb( x, y ) {
    se ( x > 10 )
        lance novo RuntimeException( "Primeiro par√¢metro maior que 10!" );
    retorne x+y;
}

xx = falso;
yy = falso;
zz = falso;
ww = falso;

tente {
    a = aa( 11,2 );
    exibaln "Resultado="+a;
} capture ( E1 | E2 e ) {
    
} capture( E3 e ) {
    xx = verdade;
} finalize {
    yy = verdade;
}


tente {
    b = bb( 11,2 );
    exibaln "Resultado="+b;
} capture ( RuntimeException e ) {
    zz = verdade;
} finalize {
    ww = verdade;
}

xxx = falso;
yyy = falso;
zzz = falso;
www = falso;
xxxx = falso;

tente {
    i = strparareal( 'a' );    
} capture( RealFormatoException e ) {
    xxx = verdade;
}

tente {
    i = strparareal( 'a' );    
} capture( Exception e ) {
    yyy = verdade;
}

tente {
    i = strparareal( 'a' );    
} capture( RuntimeException e ) {
    zzz = verdade;
}

tente {
    lance novo RuntimeException( "Mensagem de ERRO..." );
} capture ( RuntimeException e ) {
    www = verdade;
}


tente {
    tente {
        trate novo MatrizException(); 
    } capture( ValorException e ) {
        xxxx = falso;
    }
} capture ( Exception e ) {
    xxxx = verdade;
}